[package]
name = "synapse_test"
version = "0.1.0"
authors = ["pi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
synapse = { path = "../synapse" }
rand = "0.7.3"
